import json
import yaml
from typing import Dict, Any, List
from app.services.prompt_processor import CfnLoader


def parse_template(template_input: Any) -> Dict[str, Any]:
    """Parse YAML or JSON CloudFormation template into a Python dict."""
    if isinstance(template_input, dict):
        return template_input
    if isinstance(template_input, str):
        try:
            parsed = yaml.load(template_input, Loader=CfnLoader)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            pass
        try:
            return json.loads(template_input)
        except Exception:
            return {}
    return {}


def sanitize_id(name: str) -> str:
    """Sanitize resource name to be a valid Mermaid node identifier."""
    return "".join(c if c.isalnum() else "_" for c in name)


def generate_mermaid_diagram(template_input: Any) -> Dict[str, str]:
    """Generate clean, responsive Mermaid.js flowchart code from CloudFormation resources."""
    template = parse_template(template_input)
    resources = template.get("Resources", {})

    if not resources:
        return {
            "mermaid_code": "flowchart TD\n  Start[No Resources Defined in Template]"
        }

    lines: List[str] = [
        "flowchart TD",
        "  %% AWS Architecture Diagram Generated by AI Assistant",
        "  classDef vpcBox fill:#1e293b,stroke:#3b82f6,stroke-width:2px,color:#f8fafc;",
        "  classDef subnetBox fill:#0f172a,stroke:#64748b,stroke-width:1.5px,color:#f8fafc,stroke-dasharray: 4 2;",
        "  classDef ec2 fill:#ff9900,stroke:#232f3e,stroke-width:2px,color:#232f3e,font-weight:bold;",
        "  classDef rds fill:#3b82f6,stroke:#1e3a8a,stroke-width:2px,color:#ffffff,font-weight:bold;",
        "  classDef s3 fill:#10b981,stroke:#065f46,stroke-width:2px,color:#ffffff,font-weight:bold;",
        "  classDef sg fill:#8b5cf6,stroke:#4c1d95,stroke-width:1.5px,color:#ffffff;",
        "  classDef net fill:#64748b,stroke:#334155,stroke-width:1px,color:#ffffff;",
        "  classDef userNode fill:#0284c7,stroke:#0369a1,stroke-width:2px,color:#ffffff,font-weight:bold;"
    ]

    # External Client / Internet Node
    lines.append('  Client(["🌐 Public Internet / Users"]):::userNode')

    # Identify VPC and Subnets
    vpcs = {}
    subnets = {}
    ec2_instances = {}
    rds_instances = {}
    s3_buckets = {}
    security_groups = {}
    other_resources = {}

    for res_name, res_def in resources.items():
        if not isinstance(res_def, dict):
            continue
        res_type = res_def.get("Type", "Unknown")
        props = res_def.get("Properties", {})
        if not isinstance(props, dict):
            props = {}

        if res_type == "AWS::EC2::VPC":
            vpcs[res_name] = props
        elif res_type == "AWS::EC2::Subnet":
            subnets[res_name] = props
        elif res_type == "AWS::EC2::Instance":
            ec2_instances[res_name] = props
        elif res_type == "AWS::RDS::DBInstance":
            rds_instances[res_name] = props
        elif res_type == "AWS::S3::Bucket":
            s3_buckets[res_name] = props
        elif res_type == "AWS::EC2::SecurityGroup":
            security_groups[res_name] = props
        else:
            other_resources[res_name] = (res_type, props)

    # Render VPC container if present
    if vpcs:
        for vpc_name, vpc_props in vpcs.items():
            vpc_id = sanitize_id(vpc_name)
            lines.append(f'  subgraph {vpc_id} ["☁️ AWS VPC: {vpc_name}"]')
            
            # Subnets in this VPC
            for sub_name, sub_props in subnets.items():
                sub_id = sanitize_id(sub_name)
                lines.append(f'    subgraph {sub_id} ["Subnet: {sub_name}"]')
                
                # EC2 instances in this subnet
                for ec2_name, ec2_props in ec2_instances.items():
                    ec2_id = sanitize_id(ec2_name)
                    inst_type = ec2_props.get("InstanceType", "t2.micro")
                    if isinstance(inst_type, dict):
                        inst_type = "t2.micro"
                    lines.append(f'      {ec2_id}["💻 EC2: {ec2_name}<br/><i>({inst_type})</i>"]:::ec2')

                # RDS in this subnet
                for rds_name, rds_props in rds_instances.items():
                    rds_id = sanitize_id(rds_name)
                    db_class = rds_props.get("DBInstanceClass", "db.t3.micro")
                    if isinstance(db_class, dict):
                        db_class = "db.t3.micro"
                    lines.append(f'      {rds_id}[("🗄️ RDS: {rds_name}<br/><i>({db_class})</i>")]:::rds')

                lines.append("    end")
                lines.append(f"    class {sub_id} subnetBox;")
            
            lines.append("  end")
            lines.append(f"  class {vpc_id} vpcBox;")
    else:
        # No explicit VPC subgraph, render EC2 and RDS directly
        for ec2_name, ec2_props in ec2_instances.items():
            ec2_id = sanitize_id(ec2_name)
            inst_type = ec2_props.get("InstanceType", "t2.micro")
            if isinstance(inst_type, dict):
                inst_type = "t2.micro"
            lines.append(f'  {ec2_id}["💻 EC2: {ec2_name}<br/><i>({inst_type})</i>"]:::ec2')

        for rds_name, rds_props in rds_instances.items():
            rds_id = sanitize_id(rds_name)
            db_class = rds_props.get("DBInstanceClass", "db.t3.micro")
            if isinstance(db_class, dict):
                db_class = "db.t3.micro"
            lines.append(f'  {rds_id}[("🗄️ RDS: {rds_name}<br/><i>({db_class})</i>")]:::rds')

    # Render S3 Buckets outside/beside VPC
    for s3_name in s3_buckets:
        s3_id = sanitize_id(s3_name)
        lines.append(f'  {s3_id}[("🪣 S3 Bucket:<br/>{s3_name}")]:::s3')

    # Render Security Groups
    for sg_name in security_groups:
        sg_id = sanitize_id(sg_name)
        lines.append(f'  {sg_id}{{"🛡️ Security Group:<br/>{sg_name}"}}:::sg')

    # Render other notable resources
    for res_name, (res_type, _) in other_resources.items():
        res_id = sanitize_id(res_name)
        clean_type = res_type.split("::")[-1]
        lines.append(f'  {res_id}["⚙️ {clean_type}: {res_name}"]:::net')

    # Connect relationships
    # Internet -> EC2 / LoadBalancer
    if ec2_instances:
        for ec2_name in ec2_instances:
            lines.append(f'  Client -->|HTTP / HTTPS| {sanitize_id(ec2_name)}')

    # EC2 -> RDS
    if ec2_instances and rds_instances:
        for ec2_name in ec2_instances:
            for rds_name in rds_instances:
                lines.append(f'  {sanitize_id(ec2_name)} -->|Database Connection| {sanitize_id(rds_name)}')

    # EC2 -> S3
    if ec2_instances and s3_buckets:
        for ec2_name in ec2_instances:
            for s3_name in s3_buckets:
                lines.append(f'  {sanitize_id(ec2_name)} -.->|Read / Write Objects| {sanitize_id(s3_name)}')

    # Security Group -> EC2
    if security_groups and ec2_instances:
        for sg_name in security_groups:
            for ec2_name in ec2_instances:
                lines.append(f'  {sanitize_id(sg_name)} -.->|Protects| {sanitize_id(ec2_name)}')

    mermaid_code = "\n".join(lines)
    return {"mermaid_code": mermaid_code}
